using PaymentServiceLib.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace IPaymentService.Model
{
    [DataContract]
    public class PaymentRequest
    {

        /// <summary>The type of transaction to perform.</summary>
        /// <value>Type: <see cref="TransactionType"/><para>The default is <see cref="TransactionType.PurchaseCash"></see></para></value>
        [DataMember]
        public int transactionType { get; set; } = 0;

        /// <summary>The purchase amount for the transaction.</summary>
        /// <value>Type: <see cref="System.Decimal"/><para>The default is 0.</para></value>
        /// <remarks>This property is mandatory for all but <see cref="TransactionType.CashOut"></see> transaction types.</remarks>
        [DataMember]
        public decimal amtPurchase { get; set; } = 0;

        /// <summary>Tender Type</summary>
        /// <value>Type: <see cref="string"/><para></para></value>
        [DataMember]
        public TenderType tenderType { get; set; } = TenderType.Credit;

        ///// <summary>The cash amount for the transaction.</summary>
        ///// <value>Type: <see cref="System.Decimal"/><para>The default is 0.</para></value>
        ///// <remarks>This property is mandatory for a <see cref="TransactionType.CashOut"></see> transaction type.</remarks>
        [DataMember]
        public decimal amtCash { get; set; } = 0;


        /// <summary>Two digit merchant code/ Clerk ID</summary>
        /// <value>Type: <see cref="string"/><para></para></value>
        [DataMember]
        public string merchant { get; set; }

        /// <summary>AlphaNumeric Invoice Number</summary>
        /// <value>Type: <see cref="string"/><para></para></value>
        [DataMember]
        public string invoice { get; set; }

        /// <summary>AlphaNumeric CustomerReference Number</summary>
        /// <value>Type: <see cref="string"/><para></para></value>
        [DataMember]
        public string customerReference { get; set; }

        /// <summary>AlphaNumeric Optional authorization code</summary>
        /// <value>Type: <see cref="string"/><para></para></value>
        [DataMember]
        public string authCode { get; set; }

        /// <summary>Optional Reference # generated by terminal</summary>
        /// <value>Type: <see cref="string"/><para></para></value>
        [DataMember]
        public string reference { get; set; }

        /// <summary>Optional last 4 digits of account #</summary>      
        /// <value>Type: <see cref="System.String"/></value>
        /// <remarks>Use this property in conjunction with <see cref="PanSource"></see>.</remarks>
        [DataMember]
        public string pan { get; set; } = "";

        /// <summary>Indicates whether to trigger receipt events.</summary>
        /// <value>Type: <see cref="ReceiptPrintModeType"/><para>The default is POSPrinter.</para></value>
        [DataMember]
        public ReceiptPrintModeType receiptAutoPrint { get; set; } = ReceiptPrintModeType.PinpadPrinter;
    }
}
